### ISSUE TITLE
Errors when running release

### ISSUE THREAD

**Issue by bajraque** [kevinhughes27/shopify-tax-receipts#68]
I downloaded the latest code. 
Created a project in VSCode.
Pushed the code to my Heroku app: `git push heroku master`
Build ran successfully, but release fails with the following error:
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20180322143108 AddFilenameColumn: migrating ================================
-- add_column(:charities, :pdf_filename, :string, {:default=>"donation_receipt"})

**Comment by kevinhughes27** [comment]
The database probably isn't set up before the release command tries to run migrations. you'll need to disable the release command, run `db:setup` and then re-enable it.
